// Everything a visitor reads, and every piece they hear, lives here.

import type { PaintingId } from "./paintings";

/**
 * A short, true thing about the piece. `motif` names something in the
 * painting (see `motifs` in lib/paintings.ts); while the fact shows, the
 * painting dims around it. Without one the fact sits quietly in a corner.
 */
export type Fact = { text: string; motif?: string };

/**
 * A moment in the story the music tells, at `at` seconds into this recording.
 * From then until the next beat the background shows `scene` (a painting id,
 * the piece's own painting if absent), and the words show for a few seconds
 * with the light on `motif`. Cue times are matched to the recording by ear and
 * by its loudness; each beat's source is in mockups/story.md.
 */
export type Beat = { at: number; text: string; scene?: PaintingId; motif?: string };

/** Where and when a piece was written, and how it was received. Every value is sourced in mockups/details.md. */
export type PieceDetails = {
  /** As shown, e.g. "c. 1890, published 1905". */
  year: string;
  /** One year to measure the composer's age against: the year written, or the middle of a range. */
  composedYear: number;
  /** Finished before the composer's birthday that year, so they were a year younger. */
  beforeBirthday?: boolean;
  /** The date is uncertain, so the age reads "about". */
  approximate?: boolean;
  place: string;
  instruments: string;
  /** How it was received in its own time, in a sentence or two. */
  reception: string;
};

export type Composer = {
  born: number;
  died: number;
  birthplace: string;
  /** Nationality, as a gallery label gives it. */
  origin: string;
  money: string;
  /** One more short, true thing about their life. */
  also: string;
};

export type Track = {
  title: string;
  composer: ComposerName;
  performer: string;
  /** Wikimedia Commons file page, where the public-domain status is recorded. */
  source: string;
  ogg: string;
  /** Commons' own MP3 transcode of `ogg`, used where the browser plays MP3. */
  mp3: string;
  /** The background painting made for this piece. */
  painting: PaintingId;
  details: PieceDetails;
  /** Shown one at a time while the piece plays. Keep each to a sentence or two, and only what a source confirms. */
  facts: Fact[];
  /** The story the composer wrote into the music, in order, timed to this recording. */
  story?: Beat[];
};

export type Site = {
  name: string;
  tagline: string;
  description: string;
  /** Seconds from one fact to the next while music plays. */
  factSeconds: number;
  composers: typeof composers;
  tracks: Track[];
};

/** The composer's age when writing the piece, worked out from their birth year. */
export function ageAtWriting(details: PieceDetails, composer: Composer) {
  const age = details.composedYear - composer.born - (details.beforeBirthday ? 1 : 0);
  return details.approximate ? `about ${age}` : String(age);
}

/**
 * A piece's lasting id, which its likes and comments are kept under, e.g.
 * "erik-satie-gymnopedie-no-1". Renaming a piece moves it to a new id.
 */
export function pieceId(track: Pick<Track, "composer" | "title">) {
  return `${track.composer} ${track.title}`
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const composers = {
  "Erik Satie": {
    born: 1866,
    died: 1925,
    birthplace: "Honfleur, France",
    origin: "French",
    money: "Earned a modest living as a cabaret pianist and was often short of money; from 1898 he lived in one room in Arcueil.",
    also: "Left the Paris Conservatoire in 1882, then went back to study at the Schola Cantorum at 39.",
  },
  "Claude Debussy": {
    born: 1862,
    died: 1918,
    birthplace: "Saint-Germain-en-Laye, France",
    origin: "French",
    money: "Had a taste for luxury and a reputation for debts, and topped up his income by teaching and writing.",
    also: "Entered the Paris Conservatoire at ten and won the Prix de Rome in 1884.",
  },
  "Johann Sebastian Bach": {
    born: 1685,
    died: 1750,
    birthplace: "Eisenach, Germany",
    origin: "German",
    money: "A salaried musician all his life: well paid as court music director at Köthen, then cantor of St Thomas in Leipzig.",
    also: "Had 20 children; four became composers.",
  },
  "Frédéric Chopin": {
    born: 1810,
    died: 1849,
    birthplace: "Żelazowa Wola, Poland",
    origin: "Polish",
    money: "Earned a handsome income from publishing and from teaching wealthy pupils, so he rarely needed to give public concerts.",
    also: "Left Poland in 1830, never returned, and settled in Paris.",
  },
  "Robert Schumann": {
    born: 1810,
    died: 1856,
    birthplace: "Zwickau, Germany",
    origin: "German",
    money: "Clara Wieck’s father opposed their marriage, doubting he could provide for her; she was the better-known performer.",
    also: "An injured finger ended his hopes of a concert career, so he turned to composing.",
  },
  "Edvard Grieg": {
    born: 1843,
    died: 1907,
    birthplace: "Bergen, Norway",
    origin: "Norwegian",
    money: "From 1874 he received a yearly artist’s stipend from the Norwegian state.",
    also: "Trained at the Leipzig Conservatory.",
  },
  "Wolfgang Amadeus Mozart": {
    born: 1756,
    died: 1791,
    birthplace: "Salzburg, now Austria",
    origin: "Austrian",
    money: "By 1788 his income had fallen sharply, and he wrote to his friend Michael Puchberg begging for loans.",
    also: "Toured Europe’s courts as a child prodigy for three and a half years.",
  },
  "Ludwig van Beethoven": {
    born: 1770,
    died: 1827,
    birthplace: "Bonn, Germany",
    origin: "German",
    money: "From 1809, three noble patrons promised him 4,000 florins a year to stay in Vienna, though not all kept paying.",
    also: "His hearing began to fail around 1798.",
  },
  "Camille Saint-Saëns": {
    born: 1835,
    died: 1921,
    birthplace: "Paris, France",
    origin: "French",
    money: "His post as organist at La Madeleine paid comfortably, and a later legacy let him concentrate on composing.",
    also: "A child prodigy with perfect pitch before he was three.",
  },
  "Felix Mendelssohn": {
    born: 1809,
    died: 1847,
    birthplace: "Hamburg, Germany",
    origin: "German",
    money: "Came from a wealthy family; his father, Abraham, was a banker.",
    also: "In 1829 he conducted Bach’s St Matthew Passion in Berlin, sparking the Bach revival.",
  },
  "Antonín Dvořák": {
    born: 1841,
    died: 1904,
    birthplace: "Nelahozeves, Bohemia, now Czech Republic",
    origin: "Czech",
    money: "His father struggled as an innkeeper and butcher. In New York he was paid $15,000 a year, twenty-five times his Prague salary.",
    also: "Brahms sat on the jury that awarded him an Austrian state prize, and later recommended him to his own publisher.",
  },
  "Bedřich Smetana": {
    born: 1824,
    died: 1884,
    birthplace: "Litomyšl, Bohemia, now Czech Republic",
    origin: "Czech",
    money: "In 1848 he asked Liszt for a loan of 400 florins to open a music school. When deafness ended his theatre post, it offered him a pension of 1,200 florins a year.",
    also: "Gave his first public performance at six. In his homeland he is called the father of Czech music.",
  },
  "Johann Strauss II": {
    born: 1825,
    died: 1899,
    birthplace: "St Ulrich, near Vienna, Austria",
    origin: "Austrian",
    money: "His father, also a composer, wanted him to be a banker. He made his living leading his own dance orchestra, and from 1863 directed the music for Vienna’s court balls.",
    also: "Known in his lifetime as “the Waltz King”. His brothers Josef and Eduard also wrote dance music.",
  },
  "Pyotr Ilyich Tchaikovsky": {
    born: 1840,
    died: 1893,
    birthplace: "Votkinsk, Russia",
    origin: "Russian",
    money: "For 13 years the wealthy widow Nadezhda von Meck gave him an allowance so he could compose full-time. They agreed never to meet.",
    also: "Trained for the civil service and worked at the Ministry of Justice before studying music.",
  },
  "Sergei Rachmaninoff": {
    born: 1873,
    died: 1943,
    birthplace: "Semyonovo, near Staraya Russa, Russia",
    origin: "Russian",
    money: "His father’s debts cost the family its five estates. After leaving Russia in 1917 he earned his living from concert tours and recordings in the United States.",
    also: "Began the piano at four, and is widely considered one of the finest pianists of his day.",
  },
  "Modest Mussorgsky": {
    born: 1839,
    died: 1881,
    birthplace: "Karevo, Pskov Governorate, Russia",
    origin: "Russian",
    money: "Supported himself as a low-ranking civil servant until he was dismissed in 1880. Friends then raised stipends so he could finish his operas.",
    also: "Entered a military cadet school at 13. He was one of the group of Russian composers known as “The Five”.",
  },
  "Alexander Borodin": {
    born: 1833,
    died: 1887,
    birthplace: "Saint Petersburg, Russia",
    origin: "Russian",
    money: "Earned his living as a professor of chemistry at the Imperial Medical-Surgical Academy, composing in his spare time.",
    also: "A chemist of note, he also helped found medical courses for women in 1872.",
  },
  "George Frideric Handel": {
    born: 1685,
    died: 1759,
    birthplace: "Halle, Germany",
    origin: "German-British",
    money: "Received £200 a year from Queen Anne from 1713, ran his own opera companies, and died a rich man.",
    also: "Born the same year as Bach, he settled in London in 1712 and became a British subject in 1727.",
  },
  "Antonio Vivaldi": {
    born: 1678,
    died: 1741,
    birthplace: "Venice, Italy",
    origin: "Italian",
    money: "Venice’s Ospedale della Pietà paid him for two new concertos a month, but late in life he sold his manuscripts cheaply and died poor in Vienna.",
    also: "Ordained a priest at 25, he was nicknamed “the Red Priest” for his red hair.",
  },
  "Tomaso Albinoni": {
    born: 1671,
    died: 1751,
    birthplace: "Venice, Italy",
    origin: "Italian",
    money: "The son of a wealthy paper merchant, he never sought a church or court post and composed on his own means.",
    also: "He wrote at least fifty operas, most now lost; some of his music burned in Dresden in the Second World War.",
  },
  "Franz Schubert": {
    born: 1797,
    died: 1828,
    birthplace: "Vienna, Austria",
    origin: "Austrian",
    money: "Never held a steady post and often lodged with friends, who even supplied his manuscript paper; publishers paid him little.",
    also: "Wrote about 630 songs, and died at 31, a year after carrying a torch at Beethoven’s funeral.",
  },
  "Johannes Brahms": {
    born: 1833,
    died: 1897,
    birthplace: "Hamburg, Germany",
    origin: "German",
    money: "His music, the Hungarian Dances above all, earned him a good living, yet he lived modestly in Vienna.",
    also: "In 1853 Robert Schumann hailed the twenty-year-old in an article called “New Paths”.",
  },
  "Hector Berlioz": {
    born: 1803,
    died: 1869,
    birthplace: "La Côte-Saint-André, France",
    origin: "French",
    money: "His father cut his allowance when he gave up medicine, so he earned his keep writing music criticism, which he excelled at and hated.",
    also: "Never learned the piano; he played the flute and the guitar.",
  },
  "Georges Bizet": {
    born: 1838,
    died: 1875,
    birthplace: "Paris, France",
    origin: "French",
    money: "Often short of money, he taught, played for rehearsals and made piano arrangements of hundreds of operas for publishers.",
    also: "Entered the Paris Conservatoire two weeks before his tenth birthday, and won the Prix de Rome in 1857.",
  },
} satisfies Record<string, Composer>;

export type ComposerName = keyof typeof composers;

export const site: Site = {
  name: "classican",
  tagline: "Classical music to work by, and to fall in love with.",
  description:
    "A continuous playlist of public-domain classical recordings, each set to a pixel painting of what the music is about, with notes on what to listen for and the lives of the composers who wrote it. Press play and let it carry you.",
  factSeconds: 40,
  composers,
  tracks: [
    {
      title: "Gymnopédie No. 1",
      composer: "Erik Satie",
      performer: "Robin Alciatore (via Musopen)",
      source:
        "https://commons.wikimedia.org/wiki/File:Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/9/90/Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/90/Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg/Erik_Satie_-_gymnopedies_-_la_1_ere._lent_et_douloureux.ogg.mp3",
      painting: "gymnopedie",
      details: {
        year: "1888",
        composedYear: 1888,
        beforeBirthday: true,
        place: "Paris, France",
        instruments: "Solo piano",
        reception: "Little noticed at first. People began to pay attention after Debussy orchestrated it in 1897.",
      },
      facts: [
        { text: "Satie wrote his three Gymnopédies in 1888, in his early twenties.", motif: "dancers" },
        { text: "The title comes from the gymnopaedia, a festival in ancient Sparta where young men danced.", motif: "frieze" },
        { text: "Satie was playing piano in Montmartre’s cabarets, such as Le Chat Noir, around the time he wrote them.", motif: "composer" },
        { text: "The score asks for it to be played “Lent et douloureux”: slow and sorrowful." },
        { text: "Claude Debussy, Satie’s friend, later arranged two of the Gymnopédies for orchestra." },
        { text: "Listen to the left hand: it rocks gently between two soft chords while the melody floats above, never hurrying.", motif: "dancers" },
        { text: "Satie lived alone in a single room in Arcueil. After he died, friends found two pianos there, one stacked on top of the other.", motif: "composer" },
      ],
    },
    {
      title: "Clair de lune",
      composer: "Claude Debussy",
      performer: "Laurens Goedhart",
      source:
        "https://commons.wikimedia.org/wiki/File:Clair_de_lune_(Claude_Debussy)_Suite_bergamasque.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg.mp3",
      painting: "clair-de-lune",
      details: {
        year: "c. 1890, published 1905",
        composedYear: 1890,
        approximate: true,
        place: "Probably Paris, France",
        instruments: "Solo piano",
        reception: "Debussy did not want to publish this early work. He agreed in 1905, when a publisher expected his later fame to sell it.",
      },
      facts: [
        { text: "“Clair de lune” means “moonlight”. It is the third of four movements in Debussy’s Suite bergamasque.", motif: "moon" },
        { text: "The title comes from a poem by Paul Verlaine, which pictures masked dancers and fountains under the moon.", motif: "fountain" },
        { text: "Debussy began the suite around 1890 but did not publish it until 1905, revising it first." },
        { text: "It is in D-flat major, and its opening is marked pp: very softly." },
        { text: "Listen for the middle section, where the left hand breaks into rippling arpeggios, like moonlight moving on water.", motif: "fountain" },
        { text: "Debussy entered the Paris Conservatoire at ten, and spent his life bending the rules he learned there." },
      ],
    },
    {
      title: "Goldberg Variations: Aria",
      composer: "Johann Sebastian Bach",
      performer: "Kimiko Ishizaka (Open Goldberg Variations)",
      source: "https://commons.wikimedia.org/wiki/File:Goldberg_Variations_01_Aria.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/4/42/Goldberg_Variations_01_Aria.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/42/Goldberg_Variations_01_Aria.ogg/Goldberg_Variations_01_Aria.ogg.mp3",
      painting: "goldberg",
      details: {
        year: "c. 1740, published 1741",
        composedYear: 1740,
        approximate: true,
        place: "Leipzig, Germany",
        instruments: "Harpsichord with two keyboards",
        reception: "One of the few works Bach published in his lifetime. It became widely known only after Glenn Gould’s 1955 recording.",
      },
      facts: [
        { text: "Bach published the Goldberg Variations in 1741: this Aria, thirty variations, then the Aria again.", motif: "harpsichord" },
        { text: "It was written for a harpsichord with two keyboards, so the hands can cross without colliding.", motif: "keyboards" },
        { text: "Every variation is built on the bass line of this Aria, not on its tune." },
        { text: "Listen for the small trills and turns decorating the melody: Bach wrote each one into the score.", motif: "keyboards" },
        { text: "Bach’s music was little played for decades after his death, until Mendelssohn revived his St Matthew Passion in 1829." },
        { text: "Bach’s first biographer told a story that it was played to soothe a count’s sleepless nights. Historians doubt it, but the name of the young harpsichordist in the story, Goldberg, stuck.", motif: "candle" },
        { text: "Every third variation, up to the 27th, is a canon, where one voice imitates another." },
        { text: "This recording by Kimiko Ishizaka was crowdfunded and released into the public domain in 2012." },
      ],
    },
    {
      title: "Gnossienne No. 1",
      composer: "Erik Satie",
      performer: "La Pianista",
      source: "https://commons.wikimedia.org/wiki/File:Satie_-_Gnossienne_1.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/9/91/Satie_-_Gnossienne_1.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/91/Satie_-_Gnossienne_1.ogg/Satie_-_Gnossienne_1.ogg.mp3",
      painting: "gnossienne",
      details: {
        year: "c. 1890, published 1893",
        composedYear: 1890,
        approximate: true,
        place: "Paris, France",
        instruments: "Solo piano",
        reception: "How it was first received is not recorded. It was first printed in the magazine Le Figaro musical in 1893.",
      },
      facts: [
        { text: "Satie’s title may come from “gnosis”, knowledge, or from an old word for a dance of Knossos on Crete.", motif: "columns" },
        { text: "Satie wrote it without bar lines or a time signature.", motif: "stave" },
        { text: "Besides its tempo mark, “Lent”, the score whispers odd advice to the pianist, like “Très luisant” (very shiny) and “Questionnez” (ask questions)." },
        { text: "It dates from around 1890. Satie may have been inspired by music he heard at the 1889 Paris World’s Fair." },
        { text: "Listen to the bass: it plods steadily, chord after chord, while the melody above winds and twists as it pleases.", motif: "stave" },
        { text: "Satie bought seven identical grey velvet suits and wore nothing else for years, earning the nickname “the Velvet Gentleman”." },
      ],
    },
    {
      title: "Nocturne in E-flat major, Op. 9 No. 2",
      composer: "Frédéric Chopin",
      performer: "Al Goldstein collection, Pandora Music repository at ibiblio.org",
      source:
        "https://commons.wikimedia.org/wiki/File:Frederic_Chopin_-_Nocturne_Eb_major_Opus_9,_number_2.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Frederic_Chopin_-_Nocturne_Eb_major_Opus_9%2C_number_2.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5c/Frederic_Chopin_-_Nocturne_Eb_major_Opus_9%2C_number_2.ogg/Frederic_Chopin_-_Nocturne_Eb_major_Opus_9%2C_number_2.ogg.mp3",
      painting: "nocturne",
      details: {
        year: "1830–32, published 1832",
        composedYear: 1830,
        approximate: true,
        place: "On the move between Warsaw, Vienna and Paris",
        instruments: "Solo piano",
        reception: "Critics were mixed about Chopin’s nocturnes when they came out. This one is now often called his most famous piece.",
      },
      facts: [
        { text: "Chopin wrote it around 1830–31, when he was about twenty, and it was published in 1832.", motif: "piano" },
        { text: "The nocturne, a dreamy “night piece” for piano, was invented by the Irish composer John Field. Chopin made the form famous.", motif: "window" },
        { text: "Chopin left Poland in 1830 and never went back. From 1831 he made his home in Paris.", motif: "rooftops" },
        { text: "Listen each time the melody comes back: Chopin decorates it a little more, like an opera singer ornamenting a tune." },
        { text: "It is in 12/8 time: four slow beats, each divided into three." },
        { text: "Chopin disliked big concert halls. He gave only about thirty public concerts in his life, preferring the intimacy of private salons.", motif: "piano" },
      ],
    },
    {
      title: "Cello Suite No. 1 in G major: Prelude",
      composer: "Johann Sebastian Bach",
      performer: "Pablo Casals (Naxos Historical, restored by Ward Marston)",
      source: "https://commons.wikimedia.org/wiki/File:Bach_-_Cello_Suite_no._1_in_G_major,_BWV_1007_-_I._Pr%C3%A9lude.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Bach_-_Cello_Suite_no._1_in_G_major%2C_BWV_1007_-_I._Pr%C3%A9lude.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/Bach_-_Cello_Suite_no._1_in_G_major%2C_BWV_1007_-_I._Pr%C3%A9lude.ogg/Bach_-_Cello_Suite_no._1_in_G_major%2C_BWV_1007_-_I._Pr%C3%A9lude.ogg.mp3",
      painting: "cello-prelude",
      details: {
        year: "c. 1717–23",
        composedYear: 1720,
        approximate: true,
        place: "Probably Köthen, Germany",
        instruments: "Solo cello",
        reception: "The suites stayed largely unknown until Pablo Casals found an edition in 1889. His 1936–39 recordings made them famous.",
      },
      facts: [
        { text: "At thirteen, Pablo Casals found a worn copy of Bach’s cello suites in a Barcelona music shop. He practised them for over a decade before playing them in public.", motif: "score" },
        { text: "Listen for one instrument playing two parts: the cello sketches a bass line and a melody above it at the same time.", motif: "cello" },
        { text: "Bach wrote the six suites around 1720, while he was music director at the court of Köthen." },
        { text: "No copy in Bach’s own hand survives. The music reached us through copies, one of them made by his wife, Anna Magdalena." },
        { text: "Before Casals, the suites were treated mostly as exercises. His recordings from the 1930s, heard here, made them concert music." },
      ],
    },
    {
      title: "Träumerei",
      composer: "Robert Schumann",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Robert_Schumann_-_scenes_from_childhood,_op._15_-_vii._dreaming.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/0/06/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_vii._dreaming.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/06/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_vii._dreaming.ogg/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_vii._dreaming.ogg.mp3",
      painting: "traumerei",
      details: {
        year: "1838",
        composedYear: 1838,
        beforeBirthday: true,
        place: "Leipzig, Germany",
        instruments: "Solo piano",
        reception: "Clara Wieck, who married Schumann in 1840, loved the set. How the wider public first received it is less well recorded.",
      },
      facts: [
        { text: "“Träumerei” means “dreaming”. It is the seventh of thirteen short pieces in Schumann’s Scenes from Childhood, written in 1838.", motif: "dreamer" },
        { text: "Listen for the opening phrase: one long reach upward that gently settles. Almost the whole piece grows from that single gesture.", motif: "window" },
        { text: "Schumann said he gave the pieces their titles only after writing them. Another in the set is “Knight of the Hobby-Horse”.", motif: "horse" },
        { text: "He wrote them while fighting to marry the pianist Clara Wieck, whose father opposed the match. They married in 1840." },
      ],
    },
    {
      title: "Prelude in C major, BWV 846",
      composer: "Johann Sebastian Bach",
      performer: "Kimiko Ishizaka (Open Well-Tempered Clavier)",
      source: "https://commons.wikimedia.org/wiki/File:Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier,_Book_1_-_01_Prelude_No._1_in_C_major,_BWV_846.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b6/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.ogg/Kimiko_Ishizaka_-_Bach_-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.ogg.mp3",
      painting: "well-tempered",
      details: {
        year: "c. 1720–22, printed 1801",
        composedYear: 1720,
        approximate: true,
        place: "Köthen, Germany",
        instruments: "Keyboard: harpsichord or clavichord",
        reception: "It passed around in handwritten copies and was not printed until 1801, 51 years after Bach died.",
      },
      facts: [
        { text: "This prelude opens Bach’s Well-Tempered Clavier: 24 preludes and fugues, one in every major and minor key.", motif: "circle" },
        { text: "Listen for the single pattern: each bar is one chord, broken into the same rising figure and played twice. Only the harmony moves.", motif: "figure" },
        { text: "Bach compiled the book in 1722 “for the use and profit of musical youth eager to learn”." },
        { text: "More than a century later, Charles Gounod sang a new melody over this prelude, left exactly as Bach wrote it, and called it Ave Maria." },
        { text: "Kimiko Ishizaka recorded it for a crowdfunded project and gave the recording to the public domain, like her Goldberg Variations.", motif: "keyboard" },
      ],
    },
    {
      title: "Peer Gynt: Morning Mood",
      composer: "Edvard Grieg",
      performer: "Musopen Symphony (Czech National Symphony Orchestra)",
      source: "https://commons.wikimedia.org/wiki/File:Musopen_-_Morning.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Musopen_-_Morning.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/Musopen_-_Morning.ogg/Musopen_-_Morning.ogg.mp3",
      painting: "morning-mood",
      details: {
        year: "1874–75, first performed 1876",
        composedYear: 1874,
        approximate: true,
        place: "Bergen, Norway",
        instruments: "Orchestra: woodwind, horns, trumpets, timpani and strings",
        reception: "The 1876 premiere in Christiania (now Oslo) was a triumph. The Peer Gynt suites became some of Grieg’s best-known works.",
      },
      facts: [
        { text: "Grieg wrote it for Henrik Ibsen’s play Peer Gynt, first staged in 1876." },
        { text: "In the play it greets sunrise in the Moroccan desert, not over a Norwegian fjord.", motif: "desert" },
        { text: "Listen for the opening tune passing back and forth between flute and oboe, a little brighter each time.", motif: "flute" },
        { text: "Listen for the moment the whole orchestra swells, as if the sun has cleared the horizon, before it all settles again.", motif: "sun" },
        { text: "Grieg later gathered the music into two concert suites. Morning Mood opens the first." },
        { text: "Grieg’s first piano teacher was his mother, in Bergen. Later he composed in a small hut by the water at his home, Troldhaugen." },
      ],
    },
    {
      title: "Piano Sonata No. 16 in C major, K. 545: Allegro",
      composer: "Wolfgang Amadeus Mozart",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Wolfgang_Amadeus_Mozart_-_sonata_no._16_in_c_major,_k.545_%27sonata_facile%27_-_i._allegro.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/3/38/Wolfgang_Amadeus_Mozart_-_sonata_no._16_in_c_major%2C_k.545_%27sonata_facile%27_-_i._allegro.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/38/Wolfgang_Amadeus_Mozart_-_sonata_no._16_in_c_major%2C_k.545_%27sonata_facile%27_-_i._allegro.ogg/Wolfgang_Amadeus_Mozart_-_sonata_no._16_in_c_major%2C_k.545_%27sonata_facile%27_-_i._allegro.ogg.mp3",
      painting: "mozart-salon",
      details: {
        year: "1788, published 1805",
        composedYear: 1788,
        place: "Vienna, Austria",
        instruments: "Solo piano",
        reception: "Mozart called it “a little keyboard sonata for beginners”. It was not published in his lifetime.",
      },
      facts: [
        { text: "Mozart entered it in his catalogue on 26 June 1788 as “a little keyboard sonata for beginners”.", motif: "fortepiano" },
        { text: "Listen for the scales that race up and down after the opening tune: the plainest materials, made to sparkle." },
        { text: "That same summer Mozart finished his last three symphonies, in under seven weeks.", motif: "candles" },
        { text: "It was not published until 1805, fourteen years after Mozart died." },
        { text: "Mozart was composing by the age of five, and toured the courts of Europe as a child prodigy.", motif: "portrait" },
      ],
    },
    {
      title: "Air on the G String",
      composer: "Johann Sebastian Bach",
      performer: "The Air Force Strings, United States Air Force Band",
      source: "https://commons.wikimedia.org/wiki/File:Air.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/5/55/Air.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/5/55/Air.ogg/Air.ogg.mp3",
      painting: "air",
      details: {
        year: "c. 1730",
        composedYear: 1730,
        approximate: true,
        place: "Leipzig, Germany",
        instruments: "Strings and continuo",
        reception: "How it was received in Bach’s day is not recorded. It became famous through August Wilhelmj’s 1871 violin arrangement.",
      },
      facts: [
        { text: "This Air is the second movement of Bach’s Orchestral Suite No. 3 in D major, written for strings and continuo." },
        { text: "Its nickname comes from an 1871 arrangement by the violinist August Wilhelmj, who set it to be played on the violin’s lowest string alone: G.", motif: "violin" },
        { text: "Listen for the bass: it walks in steady, even steps beneath the long held notes of the melody." },
        { text: "Bach wrote the suite during his years in Leipzig, where he was cantor of St Thomas Church.", motif: "window" },
      ],
    },
    {
      title: "Moonlight Sonata: Adagio sostenuto",
      composer: "Ludwig van Beethoven",
      performer: "Paul Pitman (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27,_op._27_no._2_-_i._adagio_sostenuto.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/4/48/Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27%2C_op._27_no._2_-_i._adagio_sostenuto.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/48/Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27%2C_op._27_no._2_-_i._adagio_sostenuto.ogg/Ludwig_van_Beethoven_-_sonata_no._14_in_c_sharp_minor_%27moonlight%27%2C_op._27_no._2_-_i._adagio_sostenuto.ogg.mp3",
      painting: "moonlight",
      details: {
        year: "1801, published 1802",
        composedYear: 1801,
        beforeBirthday: true,
        approximate: true,
        place: "Vienna, Austria",
        instruments: "Solo piano",
        reception: "Already popular in his lifetime. His pupil Czerny reported him grumbling, “Surely I’ve written better things.”",
      },
      facts: [
        { text: "Beethoven never called it the Moonlight Sonata. Five years after his death, the critic Ludwig Rellstab likened it to moonlight on Lake Lucerne, and the name stuck.", motif: "lake" },
        { text: "Listen for three layers: deep octaves in the bass, a constant murmur of triplets, and above them a quiet melody, like a voice.", motif: "moon" },
        { text: "Beethoven published it in 1802 as a “sonata quasi una fantasia”: a sonata in the manner of a fantasy." },
        { text: "The score asks for the dampers to stay off throughout, so the harmonies blur softly into one another." },
        { text: "He wrote it as his hearing began to fail. In 1801 he first confided his deafness to friends in letters.", motif: "boat" },
      ],
    },
    {
      title: "The Carnival of the Animals: The Swan",
      composer: "Camille Saint-Saëns",
      performer: "Alisa Weilerstein, cello, and Jason Yoder, piano, at the White House",
      source: "https://commons.wikimedia.org/wiki/File:20091104_Alisa_Weilerstein_and_Jason_Yoder_-_Saint_Sa%C3%ABns%27_The_Swan.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/2/2a/20091104_Alisa_Weilerstein_and_Jason_Yoder_-_Saint_Sa%C3%ABns%27_The_Swan.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2a/20091104_Alisa_Weilerstein_and_Jason_Yoder_-_Saint_Sa%C3%ABns%27_The_Swan.ogg/20091104_Alisa_Weilerstein_and_Jason_Yoder_-_Saint_Sa%C3%ABns%27_The_Swan.ogg.mp3",
      painting: "swan",
      details: {
        year: "1886, published 1887",
        composedYear: 1886,
        beforeBirthday: true,
        place: "A small village in Austria, on holiday",
        instruments: "Cello and two pianos",
        reception: "Saint-Saëns banned publication of the Carnival in his lifetime, except for The Swan, which he allowed in 1887.",
      },
      facts: [
        { text: "Listen to the piano rippling like water, while the cello’s long, unbroken melody glides above it.", motif: "swan" },
        { text: "The Swan is the thirteenth of fourteen movements in Saint-Saëns’ Carnival of the Animals, written in 1886." },
        { text: "Saint-Saëns thought the Carnival too frivolous and barred its publication in his lifetime, with one exception: The Swan." },
        { text: "In 1905 the ballerina Anna Pavlova first danced The Dying Swan to it, choreographed by Michel Fokine.", motif: "reeds" },
        { text: "Saint-Saëns gave his first public recital at ten, offering to play any of Beethoven’s sonatas from memory as an encore." },
      ],
    },
    {
      title: "Venetian Gondola Song, Op. 30 No. 6",
      composer: "Felix Mendelssohn",
      performer: "Membeth (Wikimedia Commons)",
      source: "https://commons.wikimedia.org/wiki/File:Mendelssohn.Venetianisches.Gondellied.opus.30.6.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Mendelssohn.Venetianisches.Gondellied.opus.30.6.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c7/Mendelssohn.Venetianisches.Gondellied.opus.30.6.ogg/Mendelssohn.Venetianisches.Gondellied.opus.30.6.ogg.mp3",
      painting: "gondola",
      details: {
        year: "1833–34, published 1835",
        composedYear: 1833,
        approximate: true,
        place: "Probably Düsseldorf, Germany",
        instruments: "Solo piano",
        reception: "His Songs Without Words were widely popular with amateur pianists, and he went on to publish eight books of them.",
      },
      facts: [
        { text: "It comes from Mendelssohn’s Songs Without Words: short piano pieces shaped like songs, with the piano doing the singing.", motif: "gondola" },
        { text: "Listen for the lilting rhythm below, like an oar dipping and lifting, under a melody that sings like a gondolier.", motif: "gondolier" },
        { text: "Mendelssohn titled very few of these songs himself. The Venetian Gondola Songs are among the handful he named." },
        { text: "He saw Venice in 1830, on a long journey through Italy, and was a fine watercolourist who painted the places he travelled.", motif: "palazzi" },
      ],
    },
    {
      title: "Nocturne in E minor, Op. 72 No. 1",
      composer: "Frédéric Chopin",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Chopin_-_Nocturne_Op._posth._72_no._1.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Chopin_-_Nocturne_Op._posth._72_no._1.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c2/Chopin_-_Nocturne_Op._posth._72_no._1.ogg/Chopin_-_Nocturne_Op._posth._72_no._1.ogg.mp3",
      painting: "warsaw",
      details: {
        year: "1827, published 1855",
        composedYear: 1827,
        approximate: true,
        place: "Warsaw, Poland",
        instruments: "Solo piano",
        reception: "Published only after his death, so it had no audience in his lifetime. It was his first nocturne.",
      },
      facts: [
        { text: "Chopin wrote this nocturne in Warsaw around 1827, when he was about seventeen.", motif: "manuscript" },
        { text: "Listen for the left hand’s wide, rolling arpeggios, sweeping under a melody that moves as slowly as a voice." },
        { text: "It was published only in 1855, six years after his death, which is why it carries the late opus number 72.", motif: "candle" },
        { text: "Chopin left Poland at twenty and never returned, but after his death his heart was carried back to Warsaw. It rests in the Church of the Holy Cross.", motif: "window" },
      ],
    },
    {
      title: "Symphony No. 9 “From the New World”: Largo",
      composer: "Antonín Dvořák",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27,_op._95_-_ii._largo.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_ii._largo.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c3/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_ii._largo.ogg/Antonin_Dvorak_-_symphony_no._9_in_e_minor_%27from_the_new_world%27%2C_op._95_-_ii._largo.ogg.mp3",
      painting: "new-world",
      details: {
        year: "1893",
        composedYear: 1893,
        beforeBirthday: true,
        place: "New York City, United States",
        instruments: "Orchestra, with a solo cor anglais",
        reception: "A triumph: at the Carnegie Hall premiere every movement was cheered, and Dvořák stood to bow. It became one of the most popular symphonies ever written.",
      },
      facts: [
        { text: "Dvořák wrote the New World Symphony in 1893, in New York, where he was running the National Conservatory of Music.", motif: "ship" },
        { text: "Listen for the cor anglais, a deeper cousin of the oboe, singing the famous slow tune over hushed, muted strings.", motif: "horn" },
        { text: "It opens with a few soft chords in the winds. One scholar hears them as a musical “Once upon a time”." },
        { text: "Dvořák called this movement a sketch for an opera on Longfellow’s poem The Song of Hiawatha. He never wrote the opera." },
        { text: "A pupil of Dvořák’s later set the tune to words as “Goin’ Home”. It is often mistaken for an old spiritual." },
        { text: "Neil Armstrong took a tape with the New World Symphony on it to the Moon, on Apollo 11 in 1969.", motif: "moon" },
      ],
    },
    {
      title: "Má vlast: Vltava (The Moldau)",
      composer: "Bedřich Smetana",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Bedrich_Smetana_-_ma_vlast_-_i._vltava_%27the_moldau%27.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/0/08/Bedrich_Smetana_-_ma_vlast_-_i._vltava_%27the_moldau%27.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/08/Bedrich_Smetana_-_ma_vlast_-_i._vltava_%27the_moldau%27.ogg/Bedrich_Smetana_-_ma_vlast_-_i._vltava_%27the_moldau%27.ogg.mp3",
      painting: "moldau",
      details: {
        year: "1874, first performed 1875",
        composedYear: 1874,
        place: "Probably Prague, Bohemia (now Czech Republic)",
        instruments: "Orchestra, with two harps",
        reception: "First played in Prague in April 1875. It became the best known of the six poems in Má vlast and is often performed on its own.",
      },
      facts: [
        { text: "Vltava is the second of six symphonic poems in Smetana’s Má vlast, “My Fatherland”, each a picture of his native Bohemia." },
        { text: "It follows the river Vltava from two small springs, which join into one current and flow on toward Prague.", motif: "springs" },
        { text: "Listen for the music swelling from a trickle into the broad, rolling river tune: Smetana’s most famous melody.", motif: "river" },
        { text: "On the way, Smetana wrote, the river passes a farmers’ wedding, mermaids dancing by moonlight, and the St John’s Rapids.", motif: "river" },
        { text: "Near the end it flows past Vyšehrad, the high castle of the first Czech kings, and the castle’s theme returns.", motif: "castle" },
        { text: "Smetana wrote it in under three weeks at the end of 1874, just after he had become completely deaf." },
      ],
      story: [
        { at: 0, text: "Two little springs bubble up in the Bohemian forest, one warm and one cold: listen to the flutes, then the clarinets, rippling over each other.", motif: "springs" },
        { at: 70, text: "The springs join into one stream, and the violins sing the river’s own broad tune as the Vltava sets off across the country.", motif: "river" },
        { at: 200, text: "The river runs through a forest where a hunt is on: hunting horns ring out from the trees.", scene: "moldau-hunt", motif: "hunter" },
        { at: 280, text: "Past a village a farmers’ wedding is under way, and the music turns into a polka for the dancing couples.", scene: "moldau-wedding", motif: "dancers" },
        { at: 370, text: "Night falls. Water nymphs dance in the moonlight on the shining river while flutes ripple over hushed strings; castles and ruins look down from the rocks.", scene: "moldau-nymphs", motif: "nymphs" },
        { at: 525, text: "Day returns, and so does the river’s tune, flowing on.", motif: "river" },
        { at: 580, text: "The St John’s Rapids: the river hurls itself between the rocks, and the whole orchestra crashes and foams.", scene: "moldau-rapids", motif: "rapids" },
        { at: 735, text: "Through the rapids, the river widens. Its tune returns, now bright and strong in a major key, as it rolls on toward Prague.", scene: "moldau-vysehrad", motif: "river" },
        { at: 795, text: "It flows past Vyšehrad, the ancient castle of the Czech kings, and the brass call out the castle’s theme from the first poem of Má vlast.", scene: "moldau-vysehrad", motif: "castle" },
        { at: 855, text: "The river flows on out of sight, toward the Elbe, and two last chords end the journey.", scene: "moldau-vysehrad", motif: "river" },
      ],
    },
    {
      title: "Peer Gynt: In the Hall of the Mountain King",
      composer: "Edvard Grieg",
      performer: "Musopen Symphony (Czech National Symphony Orchestra)",
      source: "https://commons.wikimedia.org/wiki/File:Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/bb/Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg/Musopen_-_In_the_Hall_Of_The_Mountain_King.ogg.mp3",
      painting: "mountain-king",
      details: {
        year: "1875, first performed 1876",
        composedYear: 1875,
        approximate: true,
        place: "Bergen, Norway, and Fredensborg, Denmark",
        instruments: "Orchestra",
        reception: "The 1876 premiere of Peer Gynt in Christiania (now Oslo) was a triumph. Its tune has since become iconic in popular culture.",
      },
      facts: [
        { text: "Grieg wrote it for Ibsen’s play Peer Gynt, at the moment Peer, in a dream-like fantasy, enters the hall of the troll king.", motif: "king" },
        { text: "Its Norwegian title means “In the Dovre Man’s Hall”: Dovre is a mountain region, and the Dovre man is the troll king.", motif: "king" },
        { text: "Listen to the tune creep in slowly and quietly, low in the cellos, basses and bassoons, then speed up and grow louder until it is frantic.", motif: "trolls" },
        { text: "In the play the hall is packed with troll courtiers, gnomes and goblins, and there is “a tremendous uproar”.", motif: "trolls" },
        { text: "Grieg joked that he had written something that “reeks of cowpats” and that he could not bear to hear it.", motif: "torch" },
        { text: "It closes Grieg’s Peer Gynt Suite No. 1, published in 1888." },
      ],
    },
    {
      title: "Peer Gynt: Anitra’s Dance",
      composer: "Edvard Grieg",
      performer: "Musopen Symphony Orchestra",
      source: "https://commons.wikimedia.org/wiki/File:Grieg,_Peer_Gynt_Suite_No._1,_Op._46_-_III._Anitra%27s_Dance.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/2/25/Grieg%2C_Peer_Gynt_Suite_No._1%2C_Op._46_-_III._Anitra%27s_Dance.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/25/Grieg%2C_Peer_Gynt_Suite_No._1%2C_Op._46_-_III._Anitra%27s_Dance.ogg/Grieg%2C_Peer_Gynt_Suite_No._1%2C_Op._46_-_III._Anitra%27s_Dance.ogg.mp3",
      painting: "anitra",
      details: {
        year: "1874–75, first performed 1876",
        composedYear: 1874,
        approximate: true,
        place: "Bergen, Norway, and Fredensborg, Denmark",
        instruments: "Orchestra",
        reception: "Part of the 1876 Peer Gynt premiere, a triumph. Grieg later put it in his first Peer Gynt suite, among his best-known works.",
      },
      facts: [
        { text: "In Act IV of Ibsen’s Peer Gynt, Peer has left Norway far behind and is wandering the coast of Morocco and the desert." },
        { text: "Dressed in stolen Bedouin clothes, Peer is hailed as a prophet by a desert tribe. Anitra, the chieftain’s daughter, dances for him.", motif: "dancer" },
        { text: "Peer tries to win her, but she slips away with his money and his rings.", motif: "purse" },
        { text: "Listen for the lilting three beats: Grieg marked it “Tempo di Mazurka”, in the time of a Polish mazurka.", motif: "dancer" },
        { text: "It is the third of four pieces in Grieg’s Peer Gynt Suite No. 1, published in 1888.", motif: "lamp" },
      ],
    },
    {
      title: "Tales from the Vienna Woods, Op. 325",
      composer: "Johann Strauss II",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Johann_Strauss_-_G%27schichten_aus_dem_Wienerwald,_Op.325.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/1/19/Johann_Strauss_-_G%27schichten_aus_dem_Wienerwald%2C_Op.325.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/19/Johann_Strauss_-_G%27schichten_aus_dem_Wienerwald%2C_Op.325.ogg/Johann_Strauss_-_G%27schichten_aus_dem_Wienerwald%2C_Op.325.ogg.mp3",
      painting: "vienna-woods",
      details: {
        year: "1868",
        composedYear: 1868,
        approximate: true,
        place: "Vienna, Austria",
        instruments: "Orchestra with solo zither (or a string quartet in its place)",
        reception: "How it was first received is not well recorded. It became one of Strauss’s most famous waltzes.",
      },
      facts: [
        { text: "Strauss wrote it in 1868. Its title recalls the folk music of the people who lived in the Vienna Woods.", motif: "woods" },
        { text: "It is one of six Strauss waltzes with a starring part for the zither, a folk instrument with many strings.", motif: "zither" },
        { text: "Listen to the long introduction: a solo violin, then a flute imitating birdsong, before the waltz itself begins.", motif: "bird" },
        { text: "Its introduction runs to 119 bars, one of the longest Strauss ever wrote for a waltz." },
        { text: "If there is no zither, a string quartet plays its part instead.", motif: "zither" },
        { text: "Strauss wrote more than 500 waltzes, polkas, marches and other dances, as well as operettas." },
      ],
    },
    {
      title: "Piano Concerto No. 1 in B-flat minor: Allegro non troppo e molto maestoso",
      composer: "Pyotr Ilyich Tchaikovsky",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Tchaikovsky,_Concerto_No.1_in_B-flat_minor_Op.23,_I._Allegro.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/4/48/Tchaikovsky%2C_Concerto_No.1_in_B-flat_minor_Op.23%2C_I._Allegro.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/48/Tchaikovsky%2C_Concerto_No.1_in_B-flat_minor_Op.23%2C_I._Allegro.ogg/Tchaikovsky%2C_Concerto_No.1_in_B-flat_minor_Op.23%2C_I._Allegro.ogg.mp3",
      painting: "tchaikovsky-concerto",
      details: {
        year: "1874–75, revised 1879 and 1888",
        composedYear: 1874,
        approximate: true,
        place: "Moscow, Russia",
        instruments: "Piano and orchestra",
        reception: "Nikolai Rubinstein called it unplayable, so it premiered in Boston in 1875. The audience loved it; the critics were less impressed.",
      },
      facts: [
        { text: "Listen for the opening: the horns call out, then the piano crashes in with huge chords while the orchestra sings the big tune.", motif: "horns" },
        { text: "That grand opening tune is heard three times, then never returns in the whole concerto.", motif: "keys" },
        { text: "Tchaikovsky played it to his friend, the pianist Nikolai Rubinstein, in 1874. Rubinstein called it worthless and unplayable.", motif: "piano" },
        { text: "So the first performance went to Hans von Bülow, in Boston in 1875. By one account it was so popular he had to repeat the finale.", motif: "piano" },
        { text: "Rubinstein later took back his criticism and became one of the concerto’s greatest champions." },
        { text: "Tchaikovsky revised it twice. The 1888 version is the one usually played today." },
      ],
    },
    {
      title: "Piano Concerto No. 2 in C minor: Adagio sostenuto",
      composer: "Sergei Rachmaninoff",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Sergei_Rachmaninoff_-_piano_concerto_no._2_in_c_minor,_op._18_-_ii._adagio_sostenuto.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Sergei_Rachmaninoff_-_piano_concerto_no._2_in_c_minor%2C_op._18_-_ii._adagio_sostenuto.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a5/Sergei_Rachmaninoff_-_piano_concerto_no._2_in_c_minor%2C_op._18_-_ii._adagio_sostenuto.ogg/Sergei_Rachmaninoff_-_piano_concerto_no._2_in_c_minor%2C_op._18_-_ii._adagio_sostenuto.ogg.mp3",
      painting: "rachmaninoff-adagio",
      details: {
        year: "1900, complete concerto 1901",
        composedYear: 1900,
        place: "Probably Moscow, Russia",
        instruments: "Piano and orchestra",
        reception: "Hugely successful. The complete concerto’s 1901 premiere, with Rachmaninoff at the piano, made his name as a concerto composer.",
      },
      facts: [
        { text: "After his First Symphony’s disastrous premiere in 1897, Rachmaninoff fell into a depression and could hardly compose for three years." },
        { text: "Daily sessions with the doctor Nikolai Dahl in 1900 helped him recover. He dedicated this concerto to Dahl.", motif: "window" },
        { text: "Listen for the soft piano figure at the start, then the flute and a long clarinet solo carrying the melody.", motif: "woodwinds" },
        { text: "That opening piano figure comes from a piece he wrote in 1891 for six hands: three players at one piano.", motif: "piano" },
        { text: "He wrote this slow movement before the first one. It was premiered with the finale in December 1900, before the concerto was finished." },
        { text: "Eric Carmen’s 1975 pop song “All by Myself” is based on this movement." },
      ],
    },
    {
      title: "Pictures at an Exhibition: The Great Gate of Kiev",
      composer: "Modest Mussorgsky",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Modest_Mussorgsky_-_pictures_at_an_exhibition_-_x._la_grande_porte_de_kiev_-_allegro_alla_breve._maestoso._con_grandezza.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/be/Modest_Mussorgsky_-_pictures_at_an_exhibition_-_x._la_grande_porte_de_kiev_-_allegro_alla_breve._maestoso._con_grandezza.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Modest_Mussorgsky_-_pictures_at_an_exhibition_-_x._la_grande_porte_de_kiev_-_allegro_alla_breve._maestoso._con_grandezza.ogg/Modest_Mussorgsky_-_pictures_at_an_exhibition_-_x._la_grande_porte_de_kiev_-_allegro_alla_breve._maestoso._con_grandezza.ogg.mp3",
      painting: "great-gate",
      details: {
        year: "1874, published 1886",
        composedYear: 1874,
        place: "Saint Petersburg, Russia",
        instruments: "Written for solo piano; often played in Ravel’s 1922 orchestration",
        reception: "By one friend’s account, fellow composers were puzzled by it, and Mussorgsky set it aside unpublished. Ravel’s orchestration made it world-famous.",
      },
      facts: [
        { text: "Pictures at an Exhibition is a walk through a memorial show of works by Mussorgsky’s friend Viktor Hartmann, who died suddenly in 1873." },
        { text: "This finale pictures Hartmann’s design for city gates at Kiev, crowned by a cupola shaped like an old Slavonic helmet.", motif: "dome" },
        { text: "Hartmann’s gate won a national competition, but plans to build it were cancelled.", motif: "gate" },
        { text: "Listen for the walking “Promenade” tune from the start of the suite returning in splendour, and for music that rings like great bells.", motif: "bells" },
        { text: "Mussorgsky wrote the whole suite in three weeks, in June 1874." },
        { text: "It was not printed until 1886, five years after his death. Maurice Ravel’s 1922 version for orchestra is the one most often played." },
      ],
    },
    {
      title: "In the Steppes of Central Asia",
      composer: "Alexander Borodin",
      performer: "Musopen Symphony Orchestra",
      source: "https://commons.wikimedia.org/wiki/File:Alexander_Borodin_-_In_The_Steppes_Of_Central_Asia.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/be/Alexander_Borodin_-_In_The_Steppes_Of_Central_Asia.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Alexander_Borodin_-_In_The_Steppes_Of_Central_Asia.ogg/Alexander_Borodin_-_In_The_Steppes_Of_Central_Asia.ogg.mp3",
      painting: "steppes",
      details: {
        year: "1880",
        composedYear: 1880,
        beforeBirthday: true,
        place: "Saint Petersburg, Russia",
        instruments: "Orchestra, with a solo cor anglais",
        reception: "A concert favourite ever since its first performance in Saint Petersburg in April 1880, conducted by Rimsky-Korsakov.",
      },
      facts: [
        { text: "Borodin called it a “musical tableau”: a caravan crossing the desert of Central Asia under the protection of Russian soldiers.", motif: "caravan" },
        { text: "Listen for two tunes, a Russian song and an ornamented Eastern melody on the cor anglais. By the end they are played together.", motif: "steppe" },
        { text: "Underneath, plucked strings plod steadily on, like the hooves of horses and camels.", motif: "riders" },
        { text: "Borodin’s own note describes the caravan approaching, passing, and slowly vanishing into the immense desert.", motif: "caravan" },
        { text: "Borodin was a chemist first, a professor who composed in his spare time. He shares credit for discovering the aldol reaction." },
        { text: "He wrote it in 1880 for a celebration of Tsar Alexander II’s reign that never took place, and dedicated it to Franz Liszt." },
      ],
    },
    {
      title: "Danse macabre, Op. 40",
      composer: "Camille Saint-Saëns",
      performer: "Leopold Stokowski and the Philadelphia Orchestra (Victor, 1925)",
      source: "https://commons.wikimedia.org/wiki/File:PhiladelphiaSymphonyOrchestra-DanseMacabre.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/7/76/PhiladelphiaSymphonyOrchestra-DanseMacabre.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/76/PhiladelphiaSymphonyOrchestra-DanseMacabre.ogg/PhiladelphiaSymphonyOrchestra-DanseMacabre.ogg.mp3",
      painting: "danse-macabre",
      details: {
        year: "1874, first performed 1875",
        composedYear: 1874,
        approximate: true,
        place: "Probably Paris, France",
        instruments: "Orchestra with solo violin, xylophone and harp",
        reception: "Not well received at first: the screeching violin and rattling xylophone unsettled listeners. It is now one of his best-loved works.",
      },
      facts: [
        { text: "Listen for the harp at the very start, plucking one note twelve times: the clock striking midnight.", motif: "clock" },
        { text: "The legend goes that Death appears at midnight on Halloween and plays his fiddle while the dead dance until dawn.", motif: "death" },
        { text: "The solo violinist tunes the top string down, so Death’s first notes form a sour interval once called “the Devil in music”.", motif: "death" },
        { text: "The xylophone imitates the sound of rattling bones.", motif: "skeletons" },
        { text: "Near the end an oboe crows like a cockerel at dawn, and the skeletons hurry back to their graves.", motif: "skeletons" },
        { text: "Stokowski’s April 1925 recording of it, heard here, was the first orchestral electrical recording made in America." },
      ],
    },
    {
      title: "Jesu, Joy of Man’s Desiring",
      composer: "Johann Sebastian Bach",
      performer: "Orchestra Gli Armonici (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:Bach,_BWV_147,_10._Jesus_bleibet_meine_Freude.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/2/27/Bach%2C_BWV_147%2C_10._Jesus_bleibet_meine_Freude.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/2/27/Bach%2C_BWV_147%2C_10._Jesus_bleibet_meine_Freude.ogg/Bach%2C_BWV_147%2C_10._Jesus_bleibet_meine_Freude.ogg.mp3",
      painting: "jesu-joy",
      details: {
        year: "1723, from a 1716 cantata",
        composedYear: 1723,
        place: "Leipzig, Germany",
        instruments: "Choir, trumpet, oboes, strings and continuo",
        reception: "Written for a Leipzig church service. It became world-famous two centuries later through Myra Hess’s piano transcription.",
      },
      facts: [
        { text: "Bach wrote this chorale for a church cantata first performed in Leipzig on 2 July 1723, his first year as cantor there.", motif: "choir" },
        { text: "Listen for the flowing triplets in the orchestra: the choir’s plain hymn tune sits inside them like a stone in a stream.", motif: "triplets" },
        { text: "The hymn tune is not Bach’s own. It is by Johann Schop, from 1642; Bach wrapped it in new music." },
        { text: "He built the cantata from an Advent cantata he had written in Weimar in 1716." },
        { text: "Bach scored it for trumpet, two oboes, strings and continuo alongside the choir.", motif: "trumpet" },
        { text: "The English title is a loose rendering. The German words mean “Jesus remains my joy”." },
        { text: "Its fame today comes from the pianist Myra Hess, who published a piano transcription in 1926." },
      ],
    },
    {
      title: "Orchestral Suite No. 2 in B minor: Badinerie",
      composer: "Johann Sebastian Bach",
      performer: "European Archive (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:Bach,_Johann_Sebastian_-_Suite_No.2_in_B_Minor_-_X._Badinerie.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/9/97/Bach%2C_Johann_Sebastian_-_Suite_No.2_in_B_Minor_-_X._Badinerie.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/97/Bach%2C_Johann_Sebastian_-_Suite_No.2_in_B_Minor_-_X._Badinerie.ogg/Bach%2C_Johann_Sebastian_-_Suite_No.2_in_B_Minor_-_X._Badinerie.ogg.mp3",
      painting: "badinerie",
      details: {
        year: "c. 1738–39",
        composedYear: 1738,
        approximate: true,
        place: "Leipzig, Germany",
        instruments: "Solo flute, strings and continuo",
        reception: "How it was received in Bach’s day is not recorded. It has since become a favourite showpiece for flautists.",
      },
      facts: [
        { text: "“Badinerie” is French for “jesting”: a musical joke, quick and light.", motif: "mask" },
        { text: "It is the last movement of Bach’s Orchestral Suite No. 2, a set of dances in the French style." },
        { text: "Listen for the solo flute racing through the tune while the strings answer in short, crisp steps.", motif: "flute" },
        { text: "Its speed and difficulty have made it a favourite showpiece for solo flautists.", motif: "notes" },
        { text: "The surviving parts date from Leipzig around 1738–39. Bach wrote out the flute and viola parts himself." },
        { text: "Some scholars think the suite first existed a tone lower, with a violin or an oboe as the soloist." },
      ],
    },
    {
      title: "Harpsichord Suite No. 5 in E major: The Harmonious Blacksmith",
      composer: "George Frideric Handel",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Handel_-_Suites_for_Harpsichord_-_No.5_in_E_major_-_The_Harmonious_Blacksmith.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/d/db/Handel_-_Suites_for_Harpsichord_-_No.5_in_E_major_-_The_Harmonious_Blacksmith.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/db/Handel_-_Suites_for_Harpsichord_-_No.5_in_E_major_-_The_Harmonious_Blacksmith.ogg/Handel_-_Suites_for_Harpsichord_-_No.5_in_E_major_-_The_Harmonious_Blacksmith.ogg.mp3",
      painting: "blacksmith",
      details: {
        year: "Published 1720",
        composedYear: 1720,
        approximate: true,
        place: "Probably London, England",
        instruments: "Harpsichord",
        reception: "Handel published it in his first set of harpsichord suites in 1720. Its nickname and fame as a stand-alone piece came only in the 19th century.",
      },
      facts: [
        { text: "The tune is the last movement of Handel’s Suite No. 5, an air followed by five variations." },
        { text: "Listen for the notes getting quicker with each variation, until both hands are racing at the end." },
        { text: "In the first variation, one note repeated again and again in the right hand can sound like a hammer on an anvil.", motif: "anvil" },
        { text: "A story tells that Handel sheltered from the rain in a smithy and heard the hammer ringing. No one has ever proved it.", motif: "rain" },
        { text: "The nickname is not Handel’s. It was first recorded in the early 1800s, long after his death." },
        { text: "Another account says a Bath music seller, once a blacksmith’s apprentice, printed it under that name, which was his own nickname.", motif: "hearth" },
        { text: "Handel said he published his suites in 1720 because pirated, incorrect copies were already going around." },
      ],
    },
    {
      title: "Mandolin Concerto in C major, RV 425",
      composer: "Antonio Vivaldi",
      performer: "The Milan Baroque Soloists (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:Antonio_Vivaldi,_Mandolin_Concerto_in_C_major,_RV_425.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/6/60/Antonio_Vivaldi%2C_Mandolin_Concerto_in_C_major%2C_RV_425.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/60/Antonio_Vivaldi%2C_Mandolin_Concerto_in_C_major%2C_RV_425.ogg/Antonio_Vivaldi%2C_Mandolin_Concerto_in_C_major%2C_RV_425.ogg.mp3",
      painting: "mandolin",
      details: {
        year: "1725",
        composedYear: 1725,
        place: "Probably Venice, Italy",
        instruments: "Mandolin, strings and continuo",
        reception: "How it was first received is not recorded. Its first movement reached a new audience in the 1979 film Kramer vs. Kramer.",
      },
      facts: [
        { text: "Vivaldi wrote this concerto for mandolin, strings and continuo; it is dated to 1725.", motif: "mandolin" },
        { text: "Listen for the mandolin’s bright, plucked notes, set against the bowed strings around it.", motif: "mandolin" },
        { text: "Vivaldi taught at the Ospedale della Pietà in Venice, a home for abandoned children whose girls formed a famous orchestra.", motif: "venice" },
        { text: "Some of those girls played the mandolin: Vivaldi wrote mandolin parts for them in his oratorio Juditha triumphans." },
        { text: "Its first movement was used in the 1979 film Kramer vs. Kramer." },
        { text: "Vivaldi was ordained a priest at 25 and was nicknamed “the Red Priest” for his red hair." },
      ],
    },
    {
      title: "The Four Seasons, Spring: Allegro",
      composer: "Antonio Vivaldi",
      performer: "The Modena Chamber Orchestra (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:The_Modena_Chamber_Orchestra_-_Vivaldi%27s_Spring,_RV_269_-_I._Allegro.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/1/18/The_Modena_Chamber_Orchestra_-_Vivaldi%27s_Spring%2C_RV_269_-_I._Allegro.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/18/The_Modena_Chamber_Orchestra_-_Vivaldi%27s_Spring%2C_RV_269_-_I._Allegro.ogg/The_Modena_Chamber_Orchestra_-_Vivaldi%27s_Spring%2C_RV_269_-_I._Allegro.ogg.mp3",
      painting: "spring",
      details: {
        year: "c. 1718–23, published 1725",
        composedYear: 1720,
        approximate: true,
        place: "Probably Mantua, Italy",
        instruments: "Solo violin, strings and continuo",
        reception: "Published in Amsterdam in 1725. After long neglect it became famous again through recordings in the 1940s, and is now Vivaldi’s best-known work.",
      },
      facts: [
        { text: "Spring is the first of Vivaldi’s Four Seasons, four violin concertos published in 1725." },
        { text: "Each concerto came with a sonnet, perhaps by Vivaldi himself, describing what the music paints." },
        { text: "Listen for the birds: after the opening tune, the violins trill and chirp, as the sonnet’s “birds celebrate her return with festive song”.", motif: "birds" },
        { text: "Next come murmuring streams, then a short thunderstorm, before the birds take up their song again.", motif: "storm" },
        { text: "Listen for the soft, flowing passage that follows the birds: the streams the sonnet describes.", motif: "stream" },
        { text: "The Four Seasons is one of the earliest examples of program music: music that tells a story." },
        { text: "Bach borrowed this movement’s opening idea for an aria in one of his cantatas." },
      ],
    },
    {
      title: "Oboe Concerto in D minor, Op. 9 No. 2: Adagio",
      composer: "Tomaso Albinoni",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Albinoni,_Concerto_for_Oboe_and_Strings_No._2_in_D_minor,_Op._9,_II._Adagio.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/d/da/Albinoni%2C_Concerto_for_Oboe_and_Strings_No._2_in_D_minor%2C_Op._9%2C_II._Adagio.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/da/Albinoni%2C_Concerto_for_Oboe_and_Strings_No._2_in_D_minor%2C_Op._9%2C_II._Adagio.ogg/Albinoni%2C_Concerto_for_Oboe_and_Strings_No._2_in_D_minor%2C_Op._9%2C_II._Adagio.ogg.mp3",
      painting: "albinoni",
      details: {
        year: "Published 1722",
        composedYear: 1722,
        approximate: true,
        place: "Not documented; perhaps Munich, Germany",
        instruments: "Oboe, strings and continuo",
        reception: "The Op. 9 concertos were dedicated to the Elector of Bavaria. Albinoni’s instrumental collections met with considerable success and were reprinted.",
      },
      facts: [
        { text: "This Adagio is the slow middle movement of Albinoni’s Oboe Concerto in D minor, published in Amsterdam in 1722.", motif: "oboe" },
        { text: "Listen for the oboe holding long, singing notes over the gently pulsing strings.", motif: "oboe" },
        { text: "Albinoni was the first Italian known to write concertos with the oboe as the soloist." },
        { text: "The famous “Albinoni’s Adagio in G minor” is a different piece, largely written in the 20th century by Remo Giazotto." },
        { text: "Albinoni’s father was a wealthy paper merchant, so Albinoni could compose without a church or court job.", motif: "paper" },
        { text: "Bach admired his music and wrote fugues on Albinoni’s themes." },
      ],
    },
    {
      title: "Eine kleine Nachtmusik, K. 525: Allegro",
      composer: "Wolfgang Amadeus Mozart",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Mozart_K525_Serenade_in_G_Major_1_-_Allegro.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/6/68/Mozart_K525_Serenade_in_G_Major_1_-_Allegro.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/68/Mozart_K525_Serenade_in_G_Major_1_-_Allegro.ogg/Mozart_K525_Serenade_in_G_Major_1_-_Allegro.ogg.mp3",
      painting: "nachtmusik",
      details: {
        year: "1787, published c. 1827",
        composedYear: 1787,
        place: "Vienna, Austria",
        instruments: "Two violins, viola, cello and double bass",
        reception: "It is not known whether it was performed in Mozart’s lifetime. It was published only about 1827, sold by his widow, Constanze.",
      },
      facts: [
        { text: "“Eine kleine Nachtmusik” means “a little night music”. Mozart finished it in Vienna on 10 August 1787.", motif: "players" },
        { text: "Listen for the opening: everyone leaps upward together, a figure musicians call a “Mannheim rocket”.", motif: "rocket" },
        { text: "Mozart was working on his opera Don Giovanni at the same time." },
        { text: "Nobody knows why he wrote it, or whether it was ever played while he lived.", motif: "lantern" },
        { text: "It was written for two violins, viola, cello and double bass, though string orchestras often play it.", motif: "players" },
        { text: "Mozart listed five movements in his catalogue. One of them, a minuet, is now lost." },
      ],
    },
    {
      title: "The Magic Flute: Overture",
      composer: "Wolfgang Amadeus Mozart",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Mozart_-_Magic_Flute_Overture.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/0/08/Mozart_-_Magic_Flute_Overture.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/08/Mozart_-_Magic_Flute_Overture.ogg/Mozart_-_Magic_Flute_Overture.ogg.mp3",
      painting: "magic-flute",
      details: {
        year: "1791",
        composedYear: 1791,
        place: "Vienna, Austria",
        instruments: "Orchestra: woodwind, horns, trumpets, trombones, timpani and strings",
        reception: "The opera was an outstanding success from its first performances, drawing huge crowds and hundreds of performances in the 1790s.",
      },
      facts: [
        { text: "The Magic Flute was Mozart’s last opera, first performed in Vienna on 30 September 1791, two months before he died." },
        { text: "Mozart wrote the overture last, after the rest of the opera was finished." },
        { text: "Listen for three solemn chords from the brass at the start. Three runs through the story: three ladies, three boys, three temples.", motif: "temples" },
        { text: "After the slow opening, the strings set off on a quick fugue, one voice chasing another." },
        { text: "Halfway through, the music halts for three more chords, then the fugue starts up again.", motif: "temples" },
        { text: "In the opera, the magic flute has the power to change sorrow into joy.", motif: "flute" },
        { text: "At the premiere Mozart conducted, and the librettist Emanuel Schikaneder played the bird-catcher Papageno.", motif: "moon" },
      ],
    },
    {
      title: "Pathétique Sonata: Adagio cantabile",
      composer: "Ludwig van Beethoven",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Beethoven,_Sonata_No._8_in_C_Minor_Pathetique,_Op._13_-_II._Adagio_cantabile.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/6/63/Beethoven%2C_Sonata_No._8_in_C_Minor_Pathetique%2C_Op._13_-_II._Adagio_cantabile.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/63/Beethoven%2C_Sonata_No._8_in_C_Minor_Pathetique%2C_Op._13_-_II._Adagio_cantabile.ogg/Beethoven%2C_Sonata_No._8_in_C_Minor_Pathetique%2C_Op._13_-_II._Adagio_cantabile.ogg.mp3",
      painting: "pathetique",
      details: {
        year: "1798, published 1799",
        composedYear: 1798,
        place: "Vienna, Austria",
        instruments: "Solo piano",
        reception: "An instant success that sold well and helped make Beethoven’s name as a composer, not just as a pianist.",
      },
      facts: [
        { text: "Listen for the famous singing melody: it returns three times, always in A-flat major, with wanderings in between." },
        { text: "Beethoven wrote the sonata in 1798, aged 27, and dedicated it to his friend Prince Karl von Lichnowsky." },
        { text: "The title “Grande sonate pathétique” came from the publisher, though Beethoven liked it.", motif: "score" },
        { text: "At ten, the future pianist Ignaz Moscheles could not afford the music, so he copied it out by hand from a library copy.", motif: "copyist" },
        { text: "His teacher warned him against playing such “eccentric” new music.", motif: "shelves" },
        { text: "When the melody returns the last time, the accompaniment grows richer, carried along by triplets." },
      ],
    },
    {
      title: "Symphony No. 5 in C minor: Allegro con brio",
      composer: "Ludwig van Beethoven",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor,_op._67_-_i._allegro_con_brio.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e6/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg.mp3",
      painting: "fifth",
      details: {
        year: "1804–08, first performed 1808",
        composedYear: 1806,
        approximate: true,
        place: "Vienna, Austria",
        instruments: "Orchestra: woodwind, horns, trumpets, timpani and strings",
        reception: "The four-hour premiere in a freezing hall went badly, but within two years E. T. A. Hoffmann called it “one of the most important works of the time”.",
      },
      facts: [
        { text: "It opens with four notes, short-short-short-long: perhaps the most famous opening in music.", motif: "motif" },
        { text: "Beethoven’s secretary claimed Beethoven said of it, “Thus Fate knocks at the door!” Many scholars doubt the story.", motif: "door" },
        { text: "His pupil Carl Czerny told another story: the notes came from a yellowhammer’s song, heard in a Vienna park.", motif: "bird" },
        { text: "Listen for the four-note rhythm everywhere: it can be heard in almost every bar of this movement.", motif: "motif" },
        { text: "It premiered on 22 December 1808 in a cold hall, at a concert of Beethoven premieres lasting over four hours." },
        { text: "In the Second World War the BBC used its opening rhythm, which matches Morse code for “V”, as a victory signal." },
      ],
    },
    {
      title: "Pastoral Symphony: Allegro ma non troppo",
      composer: "Ludwig van Beethoven",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Ludwig_van_Beethoven_-_symphony_no._6_in_f_major_%27pastoral%27,_op._68_-_i._allegro_non_troppo.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Ludwig_van_Beethoven_-_symphony_no._6_in_f_major_%27pastoral%27%2C_op._68_-_i._allegro_non_troppo.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d5/Ludwig_van_Beethoven_-_symphony_no._6_in_f_major_%27pastoral%27%2C_op._68_-_i._allegro_non_troppo.ogg/Ludwig_van_Beethoven_-_symphony_no._6_in_f_major_%27pastoral%27%2C_op._68_-_i._allegro_non_troppo.ogg.mp3",
      painting: "pastoral",
      details: {
        year: "1802–08, first performed 1808",
        composedYear: 1808,
        beforeBirthday: true,
        approximate: true,
        place: "Vienna, Austria",
        instruments: "Orchestra: flutes, oboes, clarinets, bassoons, horns and strings",
        reception: "It was first played on 22 December 1808 at the Theater an der Wien in Vienna, in the same concert as his Fifth Symphony.",
      },
      facts: [
        { text: "Beethoven gave this first movement a title: “Awakening of cheerful feelings on arrival in the countryside”.", motif: "cottage" },
        { text: "He said the symphony was “more the expression of feeling than painting”: a mood of the country, not a picture of it." },
        { text: "Listen for very short motifs repeated many times over, building up the orchestra the way patterns repeat in nature.", motif: "brook" },
        { text: "A later movement has birdsong written into the score: a nightingale on the flute, a quail on the oboe, a cuckoo on two clarinets.", motif: "birds" },
        { text: "It is the Sixth Symphony, but it was premiered in the same concert as the Fifth, in December 1808." },
      ],
    },
    {
      title: "Waltz in C-sharp minor, Op. 64 No. 2",
      composer: "Frédéric Chopin",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Chopin-waltz-op-64-no-2-in-c-sharp-minor.oga",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/1/17/Chopin-waltz-op-64-no-2-in-c-sharp-minor.oga",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/17/Chopin-waltz-op-64-no-2-in-c-sharp-minor.oga/Chopin-waltz-op-64-no-2-in-c-sharp-minor.oga.mp3",
      painting: "waltz",
      details: {
        year: "1846–47, published 1847",
        composedYear: 1846,
        approximate: true,
        place: "France",
        instruments: "Solo piano",
        reception: "How it was first received is not recorded. It was published in Paris in 1847 and dedicated to Madame Nathaniel de Rothschild.",
      },
      facts: [
        { text: "Chopin wrote this waltz in 1846–47, two years before he died, and dedicated it to Madame Nathaniel de Rothschild.", motif: "chandelier" },
        { text: "Listen for three moods taking turns: a sighing opening, a quicker whirl of running notes, and a slower, warmer song in the major key.", motif: "dancers" },
        { text: "The quick whirling section keeps coming back, like a dance floor you are pulled onto again: the waltz runs A, B, C, B, A, B." },
        { text: "Orchestrated, this waltz later became part of the ballet Les Sylphides.", motif: "dancers" },
      ],
    },
    {
      title: "Ballade No. 1 in G minor, Op. 23",
      composer: "Frédéric Chopin",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Frederic_Chopin_-_ballade_no._1_in_g_minor,_op._23.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/3/33/Frederic_Chopin_-_ballade_no._1_in_g_minor%2C_op._23.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/33/Frederic_Chopin_-_ballade_no._1_in_g_minor%2C_op._23.ogg/Frederic_Chopin_-_ballade_no._1_in_g_minor%2C_op._23.ogg.mp3",
      painting: "ballade",
      details: {
        year: "1835, published 1836",
        composedYear: 1835,
        approximate: true,
        place: "Paris, France, from sketches made in Vienna in 1831",
        instruments: "Solo piano",
        reception: "Robert Schumann told Chopin it was his favourite of his works. Chopin replied that he liked it best too, his “dearest work”.",
      },
      facts: [
        { text: "The name recalls the old narrative ballad, a minstrel’s story-song. Chopin was a pioneer of the ballade as a piece for piano alone, with no words at all.", motif: "tower" },
        { text: "His friend the poet Adam Mickiewicz is said to have inspired the ballades, though what lies behind each one is not documented." },
        { text: "He sketched it in Vienna in 1831 and finished it in Paris in 1835. It was published the next year." },
        { text: "When Schumann said it was his favourite, Chopin answered: “I am glad, because I too like it the best, it is my dearest work.”" },
        { text: "Listen for the ending: a thundering chord, then a stormy, headlong coda that finishes with a fiery run of octaves down the keyboard.", motif: "storm" },
        { text: "In the 2002 film The Pianist, a performance of this ballade moves a German officer to help the hidden pianist.", motif: "sea" },
      ],
    },
    {
      title: "A Midsummer Night’s Dream: Wedding March",
      composer: "Felix Mendelssohn",
      performer: "European Archive (via Musopen)",
      source: "https://commons.wikimedia.org/wiki/File:A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_(Mendelssohn)_European_Archive.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/c/cb/A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_%28Mendelssohn%29_European_Archive.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cb/A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_%28Mendelssohn%29_European_Archive.ogg/A_Midsummer_Night%27s_Dream_Op._61_Wedding_March_%28Mendelssohn%29_European_Archive.ogg.mp3",
      painting: "wedding-march",
      details: {
        year: "1842, first performed 1843",
        composedYear: 1842,
        place: "Written for the Prussian court; first staged at Potsdam, Germany",
        instruments: "Orchestra with trumpets, trombones and percussion",
        reception: "First heard in Potsdam on 14 October 1843. After Princess Victoria chose it for her wedding in 1858, it became a favourite at weddings.",
      },
      facts: [
        { text: "Mendelssohn wrote it for Shakespeare’s A Midsummer Night’s Dream, played between Acts 4 and 5 for the weddings at the end of the play.", motif: "couple" },
        { text: "Listen for the opening trumpet fanfare, which tells you a wedding is coming before the march itself begins.", motif: "trumpets" },
        { text: "King Frederick William IV of Prussia commissioned the music in 1842, sixteen years after Mendelssohn wrote the play’s overture at seventeen." },
        { text: "In 1858, Queen Victoria’s eldest daughter, also named Victoria, walked out to this march at her wedding, and it has been played at weddings ever since.", motif: "couple" },
        { text: "Much of the play happens in an enchanted wood ruled by the fairy king and queen, Oberon and Titania.", motif: "fairies" },
      ],
    },
    {
      title: "Italian Symphony: Allegro vivace",
      composer: "Felix Mendelssohn",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Felix_Mendelssohn_-_symphony_no._4_in_a_major_%27italian%27,_op._90_-_i._allegro_vivace.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/a/af/Felix_Mendelssohn_-_symphony_no._4_in_a_major_%27italian%27%2C_op._90_-_i._allegro_vivace.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/af/Felix_Mendelssohn_-_symphony_no._4_in_a_major_%27italian%27%2C_op._90_-_i._allegro_vivace.ogg/Felix_Mendelssohn_-_symphony_no._4_in_a_major_%27italian%27%2C_op._90_-_i._allegro_vivace.ogg.mp3",
      painting: "italian",
      details: {
        year: "1830–33, first performed 1833",
        composedYear: 1833,
        place: "Begun in Italy, finished in Berlin, Germany",
        instruments: "Orchestra: pairs of woodwind, horns and trumpets, timpani and strings",
        reception: "Mendelssohn conducted the first performance in London in 1833. Still unsatisfied, he revised it and never published it; it was printed in 1851, after his death.",
      },
      facts: [
        { text: "Mendelssohn began this symphony on a long journey through Italy in 1830–31, inspired by its colour and light.", motif: "bay" },
        { text: "Listen for the bright, leaping opening: the violins race off over quick repeated chords in the woodwind, as if setting out on a sunny morning.", motif: "vesuvius" },
        { text: "He finished it in Berlin in March 1833 for the Philharmonic Society of London, and conducted the premiere there himself." },
        { text: "He was never quite happy with it, revised it, and left it unpublished. It was printed in 1851, four years after he died.", motif: "town" },
      ],
    },
    {
      title: "Piano Sonata in B-flat major, D. 960: Andante sostenuto",
      composer: "Franz Schubert",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Franz_Schubert_-_sonata_in_b_flat,_d._960_-_ii._andante_sostenuto.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Franz_Schubert_-_sonata_in_b_flat%2C_d._960_-_ii._andante_sostenuto.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e3/Franz_Schubert_-_sonata_in_b_flat%2C_d._960_-_ii._andante_sostenuto.ogg/Franz_Schubert_-_sonata_in_b_flat%2C_d._960_-_ii._andante_sostenuto.ogg.mp3",
      painting: "schubert-sonata",
      details: {
        year: "1828, published 1838–39",
        composedYear: 1828,
        place: "Vienna, Austria",
        instruments: "Solo piano",
        reception: "Published about ten years after his death, it was largely neglected in the 19th century. Serious attention came around the 1928 centenary of his death.",
      },
      facts: [
        { text: "Schubert finished this sonata in September 1828. He died two months later, on 19 November, aged 31.", motif: "sunset" },
        { text: "Listen for the left hand’s gentle rocking rhythm, repeated under a slow, sombre song.", motif: "wanderer" },
        { text: "It was one of his last three sonatas. He meant to dedicate them to the pianist Hummel, but when they appeared ten years later they were dedicated to Robert Schumann." },
        { text: "This slow movement is in C-sharp minor, an unexpectedly distant key from the sonata’s home key of B-flat major.", motif: "tree" },
        { text: "In March 1828, on the anniversary of Beethoven’s death, Schubert gave the only public concert of his own music in his life." },
      ],
    },
    {
      title: "Intermezzo in A major, Op. 118 No. 2",
      composer: "Johannes Brahms",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Johannes_Brahms_-_klavierstucke,_op._118_-_ii._intermezzo.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Johannes_Brahms_-_klavierstucke%2C_op._118_-_ii._intermezzo.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7e/Johannes_Brahms_-_klavierstucke%2C_op._118_-_ii._intermezzo.ogg/Johannes_Brahms_-_klavierstucke%2C_op._118_-_ii._intermezzo.ogg.mp3",
      painting: "intermezzo",
      details: {
        year: "1893",
        composedYear: 1893,
        place: "Bad Ischl, Austria",
        instruments: "Solo piano",
        reception: "How it was first received is not recorded. It is now among the most often played of Brahms’s late piano pieces.",
      },
      facts: [
        { text: "Brahms finished his Six Pieces, Op. 118 in the summer of 1893 at Bad Ischl, a spa town in the Austrian Alps.", motif: "mountains" },
        { text: "He dedicated the set to his lifelong friend, the pianist Clara Schumann.", motif: "letter" },
        { text: "The tempo marking is “Andante teneramente”: at a walking pace, tenderly.", motif: "rose" },
        { text: "Listen for how the opening phrase keeps returning, turned over and reshaped, as if Brahms were thinking aloud." },
        { text: "These late pieces are more inward and reflective than the showy piano music Brahms wrote as a young man." },
      ],
    },
    {
      title: "Scenes from Childhood: Of Foreign Lands and Peoples",
      composer: "Robert Schumann",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Robert_Schumann_-_scenes_from_childhood,_op._15_-_i._of_foreign_lands_and_peoples.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_i._of_foreign_lands_and_peoples.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/c/ce/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_i._of_foreign_lands_and_peoples.ogg/Robert_Schumann_-_scenes_from_childhood%2C_op._15_-_i._of_foreign_lands_and_peoples.ogg.mp3",
      painting: "foreign-lands",
      details: {
        year: "1838, published 1839",
        composedYear: 1838,
        beforeBirthday: true,
        place: "Leipzig, Germany",
        instruments: "Solo piano",
        reception: "Schumann later called these pieces more cheerful, gentler and more melodic than his earlier works. How the public first received them is less well recorded.",
      },
      facts: [
        { text: "This is the first of thirteen short pieces in Schumann’s Scenes from Childhood, the same set as Träumerei.", motif: "book" },
        { text: "Schumann said he wrote them after Clara Wieck told him he sometimes seemed “like a child”." },
        { text: "He wrote about thirty such pieces and kept thirteen. The titles came afterwards: he called them “delicate hints” for the player.", motif: "globe" },
        { text: "Listen for the simple tune over gently rippling notes, like a story about faraway places told to a child.", motif: "ship" },
      ],
    },
    {
      title: "Roman Carnival Overture, Op. 9",
      composer: "Hector Berlioz",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Hector_Berlioz_-_roman_carnival_overture,_op._9.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Hector_Berlioz_-_roman_carnival_overture%2C_op._9.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b2/Hector_Berlioz_-_roman_carnival_overture%2C_op._9.ogg/Hector_Berlioz_-_roman_carnival_overture%2C_op._9.ogg.mp3",
      painting: "roman-carnival",
      details: {
        year: "1843, first performed 1844",
        composedYear: 1843,
        approximate: true,
        place: "Paris, France",
        instruments: "Large orchestra with a solo cor anglais",
        reception: "It was first played at the Salle Herz in Paris on 3 February 1844, and became far more popular than the opera its music came from.",
      },
      facts: [
        { text: "Berlioz built this overture from his opera Benvenuto Cellini, which had only four complete performances in 1838–39." },
        { text: "Its music comes from the opera’s carnival scene, set in Rome.", motif: "lanterns" },
        { text: "Listen for the long, singing solo for the cor anglais, a deeper cousin of the oboe, early in the piece." },
        { text: "Then the music bursts into a whirling Italian dance, the saltarello, and races to a brilliant finish.", motif: "dancers" },
        { text: "Berlioz knew Rome: winning the Prix de Rome in 1830 sent him to study there for two years.", motif: "fireworks" },
      ],
    },
    {
      title: "Carmen: Prelude to Act 1",
      composer: "Georges Bizet",
      performer: "Musopen",
      source: "https://commons.wikimedia.org/wiki/File:Carmen_-_Prelude_to_Act_1.ogg",
      ogg: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Carmen_-_Prelude_to_Act_1.ogg",
      mp3: "https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9f/Carmen_-_Prelude_to_Act_1.ogg/Carmen_-_Prelude_to_Act_1.ogg.mp3",
      painting: "carmen",
      details: {
        year: "1873–74, first performed 1875",
        composedYear: 1874,
        approximate: true,
        place: "Probably Paris, France",
        instruments: "Orchestra with percussion",
        reception: "The 1875 premiere at the Opéra-Comique shocked audiences and played to half-empty houses. It became one of the most performed operas in the world.",
      },
      facts: [
        { text: "Carmen is set in southern Spain, in and around Seville, and ends outside a bullring.", motif: "bullring" },
        { text: "Listen for the swaggering march of the bullfighters, then the famous Toreador tune, then a dark, slow theme that stands for Carmen and her fate.", motif: "toreador" },
        { text: "At its premiere in Paris in March 1875, critics attacked the opera’s morality and realism." },
        { text: "Bizet died three months later, at 36, after the 33rd performance, never knowing how loved it would become.", motif: "rose" },
        { text: "Tchaikovsky saw it in Paris and called it “one of those rare creations which expresses the efforts of a whole musical epoch”." },
      ],
    },
  ],
};
